// PUBLIC_INTERFACE
export const actionTypes = {
  HYDRATE_START: "HYDRATE_START",
  HYDRATE_SUCCESS: "HYDRATE_SUCCESS",
  HYDRATE_ERROR: "HYDRATE_ERROR",

  SET_THEME: "SET_THEME",
  SET_ACTIVE_CATEGORY: "SET_ACTIVE_CATEGORY",

  UPSERT_HABIT: "UPSERT_HABIT",
  REMOVE_HABIT: "REMOVE_HABIT",

  UPSERT_CATEGORY: "UPSERT_CATEGORY",
  SET_CATEGORIES: "SET_CATEGORIES",

  SET_CHECKINS: "SET_CHECKINS",
  UPSERT_CHECKIN: "UPSERT_CHECKIN",
};
